---

version: '3.7'

services:
  db:
    image: postgres:10.11
  test:
    build:
      cache_from:
        - hexletbasics/services-web
      context: .
    command: mix test
    env_file: "./.env.docker"
    depends_on:
      - db
