---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-frontend-native-lb"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
